### ISSUE TITLE
Create useLocalStorage hook

### ISSUE THREAD

**Issue by paramsiddharth** [golu360/React-Custom-Hooks#2]
# Create `useLocalStorage` hook
The hook behaves similar to a `useState` hook, except the data is synchronized with the Local Storage API and persists within the browser's storage.

If approved and assigned, I would like to work on it as a contributor in Hacktoberfest.

**Comment by golu360** [comment]
Go ahead. 

Create a new branch corresponding to your hooks name i.e "useLocalStorage", commit your code to it and raise a PR for the same.  Please also include a working demo of the same using codesandbox.io.  Once found to be satisfactory in terms of functionality and code quality, PR will be approved.
